config/routes.rb
Rails.application.routes.draw do
  root "plays#index"
  resources :plays, only: %i[index show]
  resources :scenes, only: %i[show]
  resources :character, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :play
  has_many :lines
end

app/models/importer.rb
class Importer
  REQUIRED_METHODS = %i[
    play_title
    characters
    full_play_text
  ].freeze

  attr_accessor :play

  def initialize(module_name)
    @module_name = module_name

    self.class.class_exec do
      include module_name.constantize
    end
  end

  def run
    run_preflight
    import_data
  end

  def run_preflight
    fail("Invalid module: #{@module_name}") unless defined?(@module_name)
    REQUIRED_METHODS.each do |meth|
      fail("\n#{@module_name} must define the method: #{meth}\n\n") unless self.respond_to?(meth)
    end

    @play = Play.where(title: play_title).first_or_create!
    @characters = characters
  end

  private

  def import_data

    Line.where(scene: @play.scenes).destroy_all
    @play.scenes.destroy_all

    p 'Importing data...'

    @scene_index = 1
    @current_scene = Scene.where(play: @play, name: "Scene #{@scene_index}").first_or_create!
    @sort_order_index = 0


    char_regex = characters.map { "(#{_1})" }.join('|')
    line_regex = Regexp.new("(#{char_regex})(:|\.) (.*)", Regexp::IGNORECASE)

    full_play_text.split("\n").each do |line_of_text|
      match_data = line_regex.match(line_of_text)

      if match_data && match_data[1].present?
        create_line(char_name: match_data[1], line_text: match_data[-1])
      elsif /^\*+$/.match?(line_of_text.strip) # '****' or similar
        @scene_index = @scene_index + 1
        @sort_order_index = 0
        @current_scene = Scene.where(play: @play, name: "Scene #{@scene_index}").first_or_create!
      else
        puts "Some bum line: #{line_of_text}"
      end
    end
  end

  def create_line(char_name:, line_text:)
    char = Character.where(play: @play, name: char_name.titleize).first_or_create!

    Line.where(scene: @current_scene, character: char, sort_order: @sort_order_index)
        .first_or_create!(body: line_text)
    @sort_order_index += 1
  end
end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :scene
  belongs_to :character

  def segments
    # body.split("\n")
    words = body.split(' ')
    return [body] if words.size < 10

    avg_length_of_seg = rand(15..30)
    num_segments = words.size / avg_length_of_seg

    result = []
    jitter = (-2..2).to_a
    while words.present?
      result << words.slice!(0, [1, avg_length_of_seg + jitter.sample].max).join(' ')
    end

    result
  end
end

app/models/play.rb
class Play < ApplicationRecord
  has_many :characters
  has_many :scenes
end

app/models/scene.rb
class Scene < ApplicationRecord
  belongs_to :play
  has_many :lines
  has_many :characters, ->{ distinct }, through: :lines
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  def index
    @plays = Play.all
  end

  def show
    @play = Play.includes(scenes: { lines: :character }).find(params[:id])
  end
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  def show
    @scene = Scene.includes(:play, lines: :character).find(params[:id])
    @selected_char = @scene.characters.find_by(id: params[:character_id])
    @facade = SceneFacade.new(@scene, selected_char: @selected_char)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def character_photo(character)
    set = (character.id % 4) + 1
    photo_url = "https://robohash.org/set_set#{set}/#{character.id}?bgset=bg#{(set % 2) + 1}"
    tag.img(src: photo_url, class: 'character-photo')
  end

  def fa_icon(name, klass = '', fa_type = 'fas')
    tag.i('', class: "#{fa_type} fa-fw fa-#{name} #{klass}", 'aria-hidden': 'true')
  end
end

app/helpers/scene_helper.rb
module SceneHelper
  def line_data_attrs(line, selected_char)
    return {} unless selected_char.presence == line.character

    {
      data: {
        controller: 'line',
        'line-segments-value': line.body.split("\n")
    }}
  end

  def random_chunks(line_segment)
    words = line_segment.split(' ')
    return ['', line_segment, ''] unless words.size > 10

    idx_1 = (0..(words.size / 2)).to_a.sample
    idx_2 = ((idx_1+1)..(words.size)).to_a.sample
    chunk_1 = words.slice(0, idx_1).join(' ')
    chunk_2 = words.slice(idx_1, idx_2 - idx_1).join(' ')
    chunk_3 = words[idx_2..].join(' ')

    [chunk_1, chunk_2, chunk_3]
  end
end

app/views/characters/_picker.html.haml
-# View partials
  scene: Scene that characters can be picked from
  selected_char: Character, can be nil, depending on if a character is already selected

- selected_char ||= nil

.mb-4
  - if selected_char.present?
    Reading as
    %strong= selected_char.name
    .inline-block= character_photo(selected_char)
    = link_to 'Change character', scene_path(@scene), class: 'underline'
  - else
    Read as:
    - scene.characters.each do |char|
      = link_to char.name, scene_path(@scene, params: { character_id: char.id }), class: 'underline'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
    <%= javascript_importmap_tags %>
    <title>LineThru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://kit.fontawesome.com/6e53b97a40.js" crossorigin="anonymous"></script>
    <!--
      If using a TypeScript entrypoint file:
        vite_typescript_tag 'application'

      If using a .jsx or .tsx entrypoint, add the extension:
        vite_javascript_tag 'application.jsx'

      Visit the guide for more information: https://vite-ruby.netlify.app/guide/rails
    -->

  </head>

  <body data-turbo="true" class="bg-gray-100">
    <main class="p-8 pt-2">
      <%= yield %>
    </main>
  </body>
</html>

app/views/plays/index.html.haml
%h1.text-2xl Plays

- @plays.each do |play|
  .tw-ml-16= link_to play.title, play_path(play)

app/views/plays/show.html.haml
%h1.text-3xl.mb-4= @play.title
- @play.scenes.each do |scene|
  .card.mb-4
    .card-body
      %h2.block.text-xl= scene.name
      .default-flex-row
        = link_to 'READONLY', scene_path(scene), class: 'btn btn-outline-primary py-2'
        %div
          - scene.characters.each do |char|
            = link_to scene_path(scene, character_id: char.id), class: 'btn btn-outline-primary ml-2' do
              .flex.align-items-center
                .inline-block= character_photo(char)
                .ml-2= char.name
            -# .inline-block.mr-4= link_to char.name, scene_path(scene, character_id: char.id)

app/views/scenes/show.html.haml
= link_to @scene.play.title, play_path(@scene.play)
%h1.text-2xl.mb-4= @scene.name
= render partial: 'characters/picker', locals: { scene: @scene, selected_char: @selected_char }

%div(data-controller="scene"
     data-scene-selected-char-id-value="#{@selected_char&.id}"
     data-scene-line-ids-value="#{@scene.lines.ids}"
     data-scene-start-line-value="#{params.dig('start_line_idx') || 0}")
  - @scene.lines.each_with_index do |line, idx|
    - if line.character == @selected_char
      %div{ class: "hidden my-line",
            data: { 'scene-target': 'line', 'line-id': line.id, 'line-char-id': line.character.id }}
        .card.bg-teal-100.mb-2{line_data_attrs(line, @selected_char)}
          .card-body.flex.flex-col
            .default-flex-row
              .font-bold #{line.character.name}:
              %div(data-controller="clipboard")
                %button(class="btn btn-outline-primary ml-2" data-action="clipboard#copy")
                  = fa_icon 'link'
                .hidden.absolute.inline-block.badge.badge-primary.ml-2.mt-2(data-target="clipboard.notifier") Copied!
                .sr-only(data-target="clipboard.text")
                  = scene_url(@scene, params: { character_id: @selected_char&.id, start_line_idx: idx })
              %button.sr-only(data-line-target="skipBtn" data-action="scene#revealUntilMyLine")
            - line.segments.each do |segment|
              - chunk_1, chunk_2, chunk_3 = *random_chunks(segment)
              .pb-1.inline-block(data-controller="hidden-words"
                                 data-hidden-words-text-value="#{chunk_2}")
                .inline-block= chunk_1
                .inline-block(data-hidden-words-target="wrapper")
                  - if chunk_2.present?
                    %textarea.hidden-words.border.rounded.inline-block{
                      rows: 1,
                      cols: chunk_2.size + 2,
                      autocomplete: 'false',
                      'data-action': "keyup->hidden-words#parseInput",
                      'data-hidden-words-target': "input" }
                    %button.listen-for-line-btn(data-action="hidden-words#listen")
                      = fa_icon 'microphone-alt'
                    %span.hint-indicator(tabindex=0)
                      ❓
                      %div.hint-text= chunk_2
                .inline-block= chunk_3
            %button.border-1(data-action="line#jumpToNextLine") Skip
    - else
      %div{ class: "hidden their-line-#{@facade.index_for(line.character)}",
            data: { 'scene-target': 'line', 'line-id': line.id, 'line-char-id': line.character.id,
                    controller: 'text-to-voice', 'text-to-voice-line-body-value': line.body }}
        .card.mb-2
          .card-body
            .default-flex-row.mb-4
              %strong #{line.character.name}:
              = character_photo(line.character)
              %button.btn.btn-info(data-action="text-to-voice#speakTheSpeech" aria-label="speak the speech")
                = fa_icon 'microphone-alt'
            - line.body.split("\n").each do |line_of_text|
              %div= line_of_text